"""sync with current database

Revision ID: 00cb7f33c013
Revises: d2c1caff1299
Create Date: 2025-12-22 12:39:02.518406

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00cb7f33c013"
down_revision: Union[str, Sequence[str], None] = "d2c1caff1299"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Indexes ix_mcq_questions_document_id and ix_study_documents_user_id
    # don't exist on fresh databases, so we skip dropping them.
    # The foreign key and nullable change are also already correct in initial migration.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_progress", "selected_choice", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(None, "study_documents", type_="foreignkey")
    op.create_index(
        op.f("ix_study_documents_user_id"), "study_documents", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_mcq_questions_document_id"),
        "mcq_questions",
        ["document_id"],
        unique=False,
    )
    # ### end Alembic commands ###
